In [30]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from datetime import datetime
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [2]:
retail_data = pd.read_csv("C:/Users/HOU_User/OneDrive - Artra Technologies Pvt Ltd/Python_ML_Datasets/mock_kaggle.csv")

In [3]:
retail_data.head()

         data  venda  estoque  preco
0  2014-01-01      0     4972   1.29
1  2014-01-02     70     4902   1.29
2  2014-01-03     59     4843   1.29
3  2014-01-04     93     4750   1.29
4  2014-01-05     96     4654   1.29

In [5]:
retail_data = retail_data.rename(columns = {
    'data':'Date',
    'venda':'Sales',
    'estoque':'Stock',
    'preco':'Price',
})

In [6]:
retail_data

           Date  Sales  Stock  Price
0    2014-01-01      0   4972   1.29
1    2014-01-02     70   4902   1.29
2    2014-01-03     59   4843   1.29
3    2014-01-04     93   4750   1.29
4    2014-01-05     96   4654   1.29
..          ...    ...    ...    ...
932  2016-07-27     98   3179   2.39
933  2016-07-28    108   3071   2.39
934  2016-07-29    128   4095   2.39
935  2016-07-30    270   3825   2.39
936  2016-07-31    183   3642   2.39

[937 rows x 4 columns]

In [7]:
retail_data.Date = pd.to_datetime(retail_data.Date)

In [11]:
retail_data.Date.dtype

dtype('<M8[ns]')

In [18]:
retail_data['Is_WeekEnd'] = retail_data.Date.dt.dayofweek >=5

In [21]:
retail_data[retail_data.Is_WeekEnd == True]

          Date  Sales  Stock  Price  Is_WeekEnd
3   2014-01-04     93   4750   1.29        True
4   2014-01-05     96   4654   1.29        True
10  2014-01-11    188   5239   1.09        True
11  2014-01-12    121   5118   1.09        True
16  2014-01-18    159   4464   1.19        True
..         ...    ...    ...    ...         ...
922 2016-07-17    209    813   1.89        True
928 2016-07-23    133   1550   2.39        True
929 2016-07-24    130   1420   2.39        True
935 2016-07-30    270   3825   2.39        True
936 2016-07-31    183   3642   2.39        True

[269 rows x 5 columns]

In [ ]:
retail_data['Day_of_Week'] = retail_data.Date.dt.dayofweek # Monday=0, Sunday=6 So, Monday to Sunday = 0 to 6

In [ ]:
retail_data

          Date  Sales  Stock  Price  Is_WeekEnd  Day_of_Week
0   2014-01-01      0   4972   1.29       False            2
1   2014-01-02     70   4902   1.29       False            3
2   2014-01-03     59   4843   1.29       False            4
3   2014-01-04     93   4750   1.29        True            5
4   2014-01-05     96   4654   1.29        True            6
..         ...    ...    ...    ...         ...          ...
932 2016-07-27     98   3179   2.39       False            2
933 2016-07-28    108   3071   2.39       False            3
934 2016-07-29    128   4095   2.39       False            4
935 2016-07-30    270   3825   2.39        True            5
936 2016-07-31    183   3642   2.39        True            6

[937 rows x 6 columns]

In [24]:
retail_data['Price_per_stock'] = retail_data.Price * retail_data.Stock

In [25]:
retail_data

          Date  Sales  Stock  Price  Is_WeekEnd  Day_of_Week  Price_per_stock
0   2014-01-01      0   4972   1.29       False            2          6413.88
1   2014-01-02     70   4902   1.29       False            3          6323.58
2   2014-01-03     59   4843   1.29       False            4          6247.47
3   2014-01-04     93   4750   1.29        True            5          6127.50
4   2014-01-05     96   4654   1.29        True            6          6003.66
..         ...    ...    ...    ...         ...          ...              ...
932 2016-07-27     98   3179   2.39       False            2          7597.81
933 2016-07-28    108   3071   2.39       False            3          7339.69
934 2016-07-29    128   4095   2.39       False            4          9787.05
935 2016-07-30    270   3825   2.39        True            5          9141.75
936 2016-07-31    183   3642   2.39        True            6          8704.38

[937 rows x 7 columns]

In [26]:
retail_data['Sales_Per_Stock'] = retail_data.Sales / retail_data.Stock

In [27]:
retail_data

,Date,Sales,Stock,Price,Is_WeekEnd,Day_of_Week,Price_per_stock,Sales_Per_Stock
0,2014-01-01,0,4972,1.29,False,2,6413.88,0.000000
1,2014-01-02,70,4902,1.29,False,3,6323.58,0.014280
2,2014-01-03,59,4843,1.29,False,4,6247.47,0.012183
3,2014-01-04,93,4750,1.29,True,5,6127.50,0.019579
4,2014-01-05,96,4654,1.29,True,6,6003.66,0.020627
...,...,...,...,...,...,...,...,...
932,2016-07-27,98,3179,2.39,False,2,7597.81,0.030827
933,2016-07-28,108,3071,2.39,False,3,7339.69,0.035168
934,2016-07-29,128,4095,2.39,False,4,9787.05,0.031258
935,2016-07-30,270,3825,2.39,True,5,9141.75,0.070588
936,2016-07-31,183,3642,2.39,True,6,8704.38,0.050247

In [28]:
X_train, X_test, y_train, y_test = train_test_split(
    retail_data.drop(columns=['Date','Sales']),
    retail_data['Sales'],
    test_size=0.2,
    random_state=42
)

In [29]:
X_train

     Stock  Price  Is_WeekEnd  Day_of_Week  Price_per_stock  Sales_Per_Stock
5     4509   1.29       False            0          5816.61         0.032158
54    6412   1.09       False            3          6989.08         0.005770
275   1934   1.29       False            3          2494.86         0.050155
884   2778   2.59       False            3          7195.02         0.072354
344    578   1.29       False            2           745.62         0.271626
..     ...    ...         ...          ...              ...              ...
106   1525   1.29       False            1          1967.25         0.000000
270   1730   1.29        True            5          2231.70         0.060694
860     80   2.59       False            0           207.20         0.000000
435   1263   1.29       False            2          1629.27         0.165479
102   1742   1.29       False            4          2247.18         0.032721

[749 rows x 6 columns]

In [41]:
retail_data.isna().sum()

Date               0
Sales              0
Stock              0
Price              0
Is_WeekEnd         0
Day_of_Week        0
Price_per_stock    0
Sales_Per_Stock    0
dtype: int64

In [40]:
(retail_data == np.inf).sum()

Date               0
Sales              0
Stock              0
Price              0
Is_WeekEnd         0
Day_of_Week        0
Price_per_stock    0
Sales_Per_Stock    0
dtype: int64

In [36]:
retail_data['Sales_Per_Stock'].replace([np.inf, -np.inf], np.nan, inplace=True)

C:\Users\HOU_User\AppData\Local\Temp\ipykernel_31760\2699911284.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  retail_data['Sales_Per_Stock'].replace([np.inf, -np.inf], np.nan, inplace=True)

In [39]:
retail_data['Sales_Per_Stock'].fillna(retail_data['Sales_Per_Stock'].mean(), inplace=True)

C:\Users\HOU_User\AppData\Local\Temp\ipykernel_31760\3659385401.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  retail_data['Sales_Per_Stock'].fillna(retail_data['Sales_Per_Stock'].mean(), inplace=True)

In [43]:
X_train, X_test, y_train, y_test = train_test_split(
    retail_data.drop(columns=['Date','Sales']),
    retail_data['Sales'],
    test_size=0.2,
    random_state=42
)

In [45]:
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [46]:
y_pred = model.predict(X_test)

In [47]:
y_pred

array([0.0000e+00, 5.1130e+01, 4.4630e+01, 2.0441e+02, 9.9690e+01,
       1.2069e+02, 1.3404e+02, 1.0581e+02, 1.9850e+01, 0.0000e+00,
       1.2679e+02, 9.5840e+01, 1.9600e+00, 0.0000e+00, 6.2500e+01,
       0.0000e+00, 0.0000e+00, 3.0312e+02, 1.0331e+02, 6.5450e+01,
       2.1655e+02, 2.0631e+02, 2.1134e+02, 2.8548e+02, 0.0000e+00,
       1.0485e+02, 1.1921e+02, 2.8810e+02, 5.5690e+01, 8.6260e+01,
       2.3940e+01, 8.4740e+01, 1.8480e+01, 7.8890e+01, 6.2680e+01,
       2.5320e+01, 9.5760e+01, 9.0680e+01, 1.7078e+02, 4.5240e+01,
       8.3980e+01, 0.0000e+00, 1.5939e+02, 1.0733e+02, 1.8800e+00,
       2.5870e+01, 8.9220e+01, 4.1100e+01, 2.0330e+02, 1.4130e+01,
       8.1000e-01, 0.0000e+00, 4.8150e+01, 1.3988e+02, 1.8145e+02,
       6.1800e+01, 4.0090e+01, 0.0000e+00, 1.1145e+02, 1.0375e+02,
       7.4520e+01, 2.2282e+02, 1.6541e+02, 3.7660e+01, 3.9900e+01,
       1.6547e+02, 5.7310e+01, 6.2540e+01, 2.7419e+02, 0.0000e+00,
       0.0000e+00, 1.3424e+02, 0.0000e+00, 6.2700e+00, 8.0870e+01,
       9.3800e+01, 6.1610e+01, 6.1930e+01, 0.0000e+00, 6.5530e+01,
       3.0500e+01, 1.3404e+02, 2.6332e+02, 1.8020e+01, 1.0283e+02,
       3.1970e+01, 0.0000e+00, 1.1813e+02, 1.7123e+02, 1.6686e+02,
       0.0000e+00, 3.8570e+01, 2.9568e+02, 1.8232e+02, 6.2830e+01,
       5.2820e+01, 5.8670e+01, 1.8055e+02, 6.7580e+01, 6.9630e+01,
       0.0000e+00, 7.3400e+01, 4.9860e+01, 8.4240e+01, 7.3840e+01,
       3.6400e+01, 1.3401e+02, 2.4000e+00, 4.2510e+01, 4.6900e+00,
       6.4200e+00, 1.6244e+02, 1.8185e+02, 4.2780e+01, 9.3470e+01,
       8.6660e+01, 1.1584e+02, 1.7545e+02, 5.6360e+01, 1.9500e+02,
       1.0524e+02, 6.3620e+01, 4.2350e+01, 1.3584e+02, 1.3433e+02,
       6.3930e+01, 0.0000e+00, 2.1438e+02, 5.6380e+01, 4.6800e+00,
       1.0189e+02, 7.6600e+00, 3.5793e+02, 1.3810e+01, 1.5202e+02,
       2.9260e+01, 4.7560e+01, 1.0742e+02, 1.2652e+02, 4.7400e+01,
       2.3553e+02, 0.0000e+00, 1.9787e+02, 2.6000e-01, 8.0300e+01,
       2.0344e+02, 8.5320e+01, 4.3250e+01, 5.2040e+01, 2.0345e+02,
       0.0000e+00, 4.8140e+01, 4.3360e+01, 2.2500e+00, 9.6360e+01,
       9.8010e+01, 1.1497e+02, 2.0498e+02, 6.8690e+01, 9.7420e+01,
       5.3880e+01, 3.2859e+02, 2.4333e+02, 1.1063e+02, 6.0620e+01,
       1.0290e+02, 1.2223e+02, 1.2439e+02, 1.1627e+02, 1.8852e+02,
       1.0900e+02, 7.6490e+01, 1.7822e+02, 6.4850e+01, 1.0384e+02,
       3.6940e+01, 1.1880e+01, 7.2980e+01, 1.2700e+01, 1.3780e+02,
       1.1317e+02, 0.0000e+00, 5.7140e+01, 1.3028e+02, 5.7350e+01,
       3.0800e+01, 0.0000e+00, 2.9760e+01])

In [48]:
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

In [49]:
mse

1423.3927819148935

In [50]:
mae

11.979148936170212

In [51]:
Comparison = pd.DataFrame(
    {
        'Actual': y_test,
        'Predicted': y_pred
    }
)

In [52]:
print(Comparison)

     Actual  Predicted
321       0       0.00
70       48      51.13
209      45      44.63
656     257     204.41
685      76      99.69
..      ...        ...
847     125     130.28
2        59      57.35
456      30      30.80
331       0       0.00
408      31      29.76

[188 rows x 2 columns]